import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#080c18',
  '--slot4-page-text': '#e8ecf4',
  '--slot4-panel-bg': '#0d1224',
  '--slot4-surface-bg': '#111827',
  '--slot4-muted-text': '#8b95b0',
  '--slot4-soft-muted-text': '#5e6a85',
  '--slot4-accent': '#38bdf8',
  '--slot4-accent-fill': '#38bdf8',
  '--slot4-accent-soft': 'rgba(56,189,248,0.1)',
  '--slot4-on-accent': '#080c18',
  '--slot4-dark-bg': '#060a15',
  '--slot4-dark-text': '#e8ecf4',
  '--slot4-media-bg': '#0f1629',
  '--slot4-cream': '#0d1224',
  '--slot4-warm': '#0a0f1e',
  '--slot4-lavender': '#111827',
  '--slot4-gray': '#0d1224',
  '--slot4-body-gradient': 'linear-gradient(180deg, #080c18 0%, #0a1020 50%, #080c18 100%)',
  '--editable-page-bg': '#080c18',
  '--editable-page-text': '#e8ecf4',
  '--editable-container': '1400px',
  '--editable-border': 'rgba(255,255,255,0.08)',
  '--editable-nav-bg': 'rgba(8,12,24,0.85)',
  '--editable-nav-text': '#e8ecf4',
  '--editable-nav-active': '#38bdf8',
  '--editable-nav-active-text': '#080c18',
  '--editable-cta-bg': '#ffffff',
  '--editable-cta-text': '#080c18',
  '--editable-search-bg': '#111827',
  '--editable-footer-bg': '#060a15',
  '--editable-footer-text': '#e8ecf4',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_4px_24px_rgba(0,0,0,0.4)]',
  shadowStrong: 'shadow-[0_8px_40px_rgba(0,0,0,0.6)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-bold leading-[1.08] tracking-[-0.03em] sm:text-5xl lg:text-[3.25rem]',
    sectionTitle: 'text-3xl font-bold tracking-[-0.02em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-2xl border border-white/[0.06] bg-[#111827] ${editablePalette.shadow}`,
    soft: `rounded-2xl border border-white/[0.06] bg-[#0d1224]`,
    dark: `rounded-2xl bg-[#060a15] text-[#e8ecf4] ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-white px-7 py-3.5 text-sm font-bold tracking-[0.01em] text-[#080c18] transition duration-300 hover:bg-white/90 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-white/15 bg-white/5 px-7 py-3.5 text-sm font-bold tracking-[0.01em] text-white/90 transition duration-300 hover:bg-white/10 active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-110 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-2xl bg-[#0f1629]`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1.5 hover:shadow-[0_16px_48px_rgba(0,0,0,0.5)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
